Repository innohack2021/HotSource, pull requests merged in 2021-11, with the labels that each got.

#2 Env: Github 기본 세팅
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labels.json
Labels: Priority: medium, Environment

#4 TEST: 기능구현과 관련된 기본적 testcase 작성
  .TESTCASE/default_case1.json
  .TESTCASE/default_error1.json
  .TESTCASE/default_error2.json
  .TESTCASE/default_error3.json
Labels: Priority: high, good first issue

#10 Env: .gitignore 업데이트
  .gitignore
Labels: Environment, Priority: very high

#12 Enhancement: Gradle 프로젝트 생성
  build.gradle
  build/tmp/compileJava/previous-compilation-data.bin
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/innohotsource/hotjson/Hello.java
Labels: Enhancement

#7 Env: github action ci.yml 추가
  .github/workflows/ci.yml
Labels: Environment, Priority: very high

#14 Enhancement: .gitignore 수정
  .gitignore
Labels: Enhancement, Environment

#15 Env: 불필요하게 추가된 파일 삭제
  build/tmp/compileJava/previous-compilation-data.bin
Labels: Environment

#16 Env: 디렉토리를 추가하기 위한 더미파일 생성
  src/main/resources/dummy.txt
  src/test/java/com/innohotsource/hotjson/HelloTest.java
  src/test/resources/dummy.txt
Labels: Environment, Priority: high

#19 Env: simple-json 의존성 추가
  build.gradle
  src/main/java/com/innohotsource/hotjson/Json/Attribute.java
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
  src/main/java/com/innohotsource/hotjson/annotation/IgnoredField.java
Labels: Environment, Priority: very high

#21 Study : Reflection
  GUIDELINE/reflection.md
  GUIDELINE/step1_Reflection.md
Labels: Study

#22 Study: Annotation
  GUIDELINE/step2_Annotation.md
Labels: Study

#23 Env: SonarCloud 설치
  .github/workflow/ci.yaml
  .github/workflows/build.yml
  build.gradle
Labels: Environment, Priority: high

#25 Study : step3_JsonParser
  GUIDELINE/reflection.md
  GUIDELINE/step2_Annotation.md
  GUIDELINE/step3_JsonParser.md
Labels: Study

#26 Add JSON에서 엔티티 변환
  src/main/java/com/innohotsource/hotjson/Json/JsonToObject.java
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
  src/test/java/com/innohotsource/hotjson/Json/JsonToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/Sample.java
Labels: Enhancement, Priority: very high

#27 Study : (optional) step4_github.md
  GUIDELINE/(optional)step4_Github.md
  GUIDELINE/img/2.clone.JPG
  GUIDELINE/img/6comparepull.JPG
  GUIDELINE/img/6pr_list.JPG
  GUIDELINE/img/Merge1.JPG
  GUIDELINE/img/Merge2.JPG
  GUIDELINE/img/Merge3.JPG
  GUIDELINE/img/Merge4.JPG
  GUIDELINE/img/create_branch.JPG
  GUIDELINE/img/fetchandmerge.JPG
  GUIDELINE/img/fetchandmerge2.JPG
  GUIDELINE/img/fork.JPG
  GUIDELINE/img/image.JPG
  GUIDELINE/img/issue1.JPG
  GUIDELINE/img/issue2.JPG
  GUIDELINE/img/ssh.JPG
  GUIDELINE/img/switch_branch.JPG
  GUIDELINE/step1_Reflection.md
Labels: Documentation, Study

#29 Enhance: Object -> JSONObject 변환 기능 추가
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
Labels: Enhancement, Priority: high

#30 docs : GUIDELINE 폴더 수정
  GUIDELINE/img/2.clone.JPG
  GUIDELINE/img/6comparepull.JPG
  GUIDELINE/img/6pr_list.JPG
  GUIDELINE/img/Merge1.JPG
  GUIDELINE/img/Merge2.JPG
  GUIDELINE/img/Merge3.JPG
  GUIDELINE/img/Merge4.JPG
  GUIDELINE/img/create_branch.JPG
  GUIDELINE/img/fetchandmerge.JPG
  GUIDELINE/img/fetchandmerge2.JPG
  GUIDELINE/img/fork.JPG
  GUIDELINE/img/image.JPG
  GUIDELINE/img/issue1.JPG
  GUIDELINE/img/issue2.JPG
  GUIDELINE/img/ssh.JPG
  GUIDELINE/img/switch_branch.JPG
  GUIDELINE/reflection.md
  GUIDELINE/step1_Reflection.md
  GUIDELINE/step2_Annotation.md
  GUIDELINE/step3_JsonParser.md
  GUIDELINE/step4_Github.md
Labels: Documentation, Study

#33 FIX : JSON 변환 초기 기능 구현 완료
  .github/workflows/build.yml
  GUIDELINE/(optional)step4_Github.md
  GUIDELINE/img/2.clone.JPG
  GUIDELINE/img/6comparepull.JPG
  GUIDELINE/img/6pr_list.JPG
  GUIDELINE/img/Merge1.JPG
  GUIDELINE/img/Merge2.JPG
  GUIDELINE/img/Merge3.JPG
  GUIDELINE/img/Merge4.JPG
  GUIDELINE/img/create_branch.JPG
  GUIDELINE/img/fetchandmerge.JPG
  GUIDELINE/img/fetchandmerge2.JPG
  GUIDELINE/img/fork.JPG
  GUIDELINE/img/image.JPG
  GUIDELINE/img/issue1.JPG
  GUIDELINE/img/issue2.JPG
  GUIDELINE/img/ssh.JPG
  GUIDELINE/img/switch_branch.JPG
  GUIDELINE/step1_Reflection.md
  GUIDELINE/step2_Annotation.md
  GUIDELINE/step3_JsonParser.md
  src/main/java/com/innohotsource/hotjson/Json/JsonToObject.java
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
  src/test/java/com/innohotsource/hotjson/Json/JsonToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/Sample.java
  src/test/java/com/innohotsource/hotjson/Json/Sub.java
  src/test/java/com/innohotsource/hotjson/Json/SubSample.java
Labels: Enhancement, Priority: very high

#36 Fix : JSONObject에서 List Type을 받아오는 기능
  .github/workflows/SonarCloud.yml
  build.gradle
  src/main/java/com/innohotsource/hotjson/Json/JsonToObject.java
  src/test/java/com/innohotsource/hotjson/Json/JsonListToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/Sample.java
  src/test/java/com/innohotsource/hotjson/Json/Sample1.java
  src/test/java/com/innohotsource/hotjson/Json/Sub.java
  src/test/java/com/innohotsource/hotjson/Json/SubSampleList.java
Labels: Enhancement, Priority: very high

#38 Refactor : JsonToObject 중심으로 코드 수정
  .github/workflows/SonarCloud.yml
  src/main/java/com/innohotsource/hotjson/Hello.java
  src/main/java/com/innohotsource/hotjson/Json/Attribute.java
  src/main/java/com/innohotsource/hotjson/Json/JsonToObject.java
  src/test/java/com/innohotsource/hotjson/Json/JsonListToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/Sample1.java
Labels: Bug, Priority: low

#39 docs : step1,2,3,4 추가
  GUIDELINE/img/2.clone.JPG
  GUIDELINE/img/6comparepull.JPG
  GUIDELINE/img/6pr_list.JPG
  GUIDELINE/img/Merge1.JPG
  GUIDELINE/img/Merge2.JPG
  GUIDELINE/img/Merge3.JPG
  GUIDELINE/img/Merge4.JPG
  GUIDELINE/img/create_branch.JPG
  GUIDELINE/img/fetchandmerge.JPG
  GUIDELINE/img/fetchandmerge2.JPG
  GUIDELINE/img/fork.JPG
  GUIDELINE/img/image.JPG
  GUIDELINE/img/issue1.JPG
  GUIDELINE/img/issue2.JPG
  GUIDELINE/img/ssh.JPG
  GUIDELINE/img/switch_branch.JPG
  GUIDELINE/step1_Reflection.md
  GUIDELINE/step2_Annotation.md
  GUIDELINE/step3_JsonParser.md
  GUIDELINE/step4_Github.md
Labels: Documentation, Study

#40 Refactor: JsonToObject 조건문 수정
  src/main/java/com/innohotsource/hotjson/Json/JsonToObject.java
  src/test/java/com/innohotsource/hotjson/Json/JsonListToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/JsonToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/Sub.java
  src/test/java/com/innohotsource/hotjson/Json/sample/Sample.java
  src/test/java/com/innohotsource/hotjson/Json/sample/Sample1.java
  src/test/java/com/innohotsource/hotjson/Json/sample/Sub.java
  src/test/java/com/innohotsource/hotjson/Json/sample/SubSample.java
  src/test/java/com/innohotsource/hotjson/Json/sample/SubSampleList.java
Labels: Priority: low, Test

#43 Enhancement : File -> instance 로 변환하는 기능 추가
  src/main/java/com/innohotsource/hotjson/Json/FileToObject.java
  src/test/java/com/innohotsource/hotjson/Json/FileToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/JsonToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/samplefile/Sample.json
Labels: Enhancement, Priority: low

#44 Fix : ListType 초기화 해결
  src/main/java/com/innohotsource/hotjson/Json/FileToObject.java
  src/main/java/com/innohotsource/hotjson/Json/JsonToObject.java
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
  src/main/java/com/innohotsource/hotjson/annotation/NotNull.java
  src/test/java/com/innohotsource/hotjson/Json/FileToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/JsonListToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/JsonToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/sample/Sample1.java
  src/test/java/com/innohotsource/hotjson/Json/sample/SubSample.java
  src/test/java/com/innohotsource/hotjson/Json/sample/SubSampleList.java
Labels: Bug, Priority: very high

#47 Enhance: object 에서 JSONObject 변환시 단일 리스트 맵 기능 추가
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
Labels: Enhancement, Priority: high

#49 Enhance: 중첩된 List 및 Map 처리
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
Labels: Enhancement, Priority: high

#51 Enhance: object -> JSONObject Array 필드 구현
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
Labels: Enhancement, Priority: high

#52 String 입력 받는 기능 구현, fromJson 입력 받는 타입 변경
  src/main/java/com/innohotsource/hotjson/Json/Attribute.java
  src/main/java/com/innohotsource/hotjson/Json/JsonToObject.java
  src/test/java/com/innohotsource/hotjson/Json/FileToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/JsonListToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/JsonToObjectTest.java
Labels: Bug, Enhancement, Priority: very high

#55 docs : github.md 수정
  GUIDELINE/step4_Github.md
Labels: Documentation, Study

#54 Bug : JsonToObject 수정에 따른 FileToObject 코드 수정
  build.gradle
  src/main/java/com/innohotsource/hotjson/Json/FileToObject.java
  src/test/java/com/innohotsource/hotjson/Json/FileToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/JsonListToObjectTest.java
  src/test/java/com/innohotsource/hotjson/Json/sample/Sample.java
  src/test/java/com/innohotsource/hotjson/Json/sample/SubSampleList.java
Labels: Bug, Priority: medium

#56 FileToObeject 테스트 코드 변경 및 readme.md 추가
  README.md
  src/test/java/com/innohotsource/hotjson/Json/FileToObjectTest.java
Labels: Test

#57 Enhance: object -> String 추가
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
Labels: Enhancement, Priority: high

#59 Enhance: 주석추가
  src/main/java/com/innohotsource/hotjson/Json/ObjectToJson.java
Labels: Enhancement, Priority: medium

#61 readme.md 수정 및 FileToObject.java 버그 수정
  README.md
  src/main/java/com/innohotsource/hotjson/Json/FileToObject.java
Labels: Bug, Documentation
